package CapaDatos;
// Generated 10/07/2015 23:07:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Direccion generated by hbm2java
 */
@Entity
@Table(name="direccion"
    ,catalog="procesosproyectofinaldb"
)
public class Direccion  implements java.io.Serializable {


     private Integer iddireccion;
     private Integer directorPy;
     private Integer auxiliar1;
     private Integer auxiliar2;
     private Set proyectofts = new HashSet(0);
     private Set proyectofts_1 = new HashSet(0);

    public Direccion() {
    }

    public Direccion(Integer directorPy, Integer auxiliar1, Integer auxiliar2, Set proyectofts, Set proyectofts_1) {
       this.directorPy = directorPy;
       this.auxiliar1 = auxiliar1;
       this.auxiliar2 = auxiliar2;
       this.proyectofts = proyectofts;
       this.proyectofts_1 = proyectofts_1;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="iddireccion", unique=true, nullable=false)
    public Integer getIddireccion() {
        return this.iddireccion;
    }
    
    public void setIddireccion(Integer iddireccion) {
        this.iddireccion = iddireccion;
    }

    
    @Column(name="director_py")
    public Integer getDirectorPy() {
        return this.directorPy;
    }
    
    public void setDirectorPy(Integer directorPy) {
        this.directorPy = directorPy;
    }

    
    @Column(name="auxiliar1")
    public Integer getAuxiliar1() {
        return this.auxiliar1;
    }
    
    public void setAuxiliar1(Integer auxiliar1) {
        this.auxiliar1 = auxiliar1;
    }

    
    @Column(name="auxiliar2")
    public Integer getAuxiliar2() {
        return this.auxiliar2;
    }
    
    public void setAuxiliar2(Integer auxiliar2) {
        this.auxiliar2 = auxiliar2;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="direccion")
    public Set getProyectofts() {
        return this.proyectofts;
    }
    
    public void setProyectofts(Set proyectofts) {
        this.proyectofts = proyectofts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="direccion")
    public Set getProyectofts_1() {
        return this.proyectofts_1;
    }
    
    public void setProyectofts_1(Set proyectofts_1) {
        this.proyectofts_1 = proyectofts_1;
    }




}


