package CapaDatos;
// Generated 10/07/2015 23:07:03 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Propuesta generated by hbm2java
 */
@Entity
@Table(name="propuesta"
    ,catalog="procesosproyectofinaldb"
)
public class Propuesta  implements java.io.Serializable {


     private Integer idpropuesta;
     private SeccionDep seccionDep;
     private Usuario usuario;
     private String nombreP;
     private Integer estadoP;
     private String descripcionP;
     private Date fechaP;
     private Integer comiteIdcomite;
     private String comentarioP;

    public Propuesta() {
        this.estadoP=1;
    }

    public Propuesta(SeccionDep seccionDep, Usuario usuario, String nombreP, Integer estadoP, String descripcionP, Date fechaP, Integer comiteIdcomite, String comentarioP) {
       this.seccionDep = seccionDep;
       this.usuario = usuario;
       this.nombreP = nombreP;
       this.estadoP = estadoP;
       this.descripcionP = descripcionP;
       this.fechaP = fechaP;
       this.comiteIdcomite = comiteIdcomite;
       this.comentarioP = comentarioP;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idpropuesta", unique=true, nullable=false)
    public Integer getIdpropuesta() {
        return this.idpropuesta;
    }
    
    public void setIdpropuesta(Integer idpropuesta) {
        this.idpropuesta = idpropuesta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idsecd")
    public SeccionDep getSeccionDep() {
        return this.seccionDep;
    }
    
    public void setSeccionDep(SeccionDep seccionDep) {
        this.seccionDep = seccionDep;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idusu")
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="nombre_p", length=300)
    public String getNombreP() {
        return this.nombreP;
    }
    
    public void setNombreP(String nombreP) {
        this.nombreP = nombreP;
    }

    
    @Column(name="estado_p")
    public Integer getEstadoP() {
        return this.estadoP;
    }
    
    public void setEstadoP(Integer estadoP) {
        this.estadoP = estadoP;
    }

    
    @Column(name="descripcion_p", length=500)
    public String getDescripcionP() {
        return this.descripcionP;
    }
    
    public void setDescripcionP(String descripcionP) {
        this.descripcionP = descripcionP;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_p", length=10)
    public Date getFechaP() {
        return this.fechaP;
    }
    
    public void setFechaP(Date fechaP) {
        this.fechaP = fechaP;
    }

    
    @Column(name="comite_idcomite")
    public Integer getComiteIdcomite() {
        return this.comiteIdcomite;
    }
    
    public void setComiteIdcomite(Integer comiteIdcomite) {
        this.comiteIdcomite = comiteIdcomite;
    }

    
    @Column(name="comentario_p", length=500)
    public String getComentarioP() {
        return this.comentarioP;
    }
    
    public void setComentarioP(String comentarioP) {
        this.comentarioP = comentarioP;
    }




}


